#!/usr/bin/env python3
import argparse
import concurrent.futures
import ipaddress
import os
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"

DEFAULTS = {
    "AFTERTOUCH_HTTP_PORT": "8091",
    "AFTERTOUCH_HTTPS_PORT": "8444",
    "PROXY_PORT": "8092",
}


def log(message):
    print(message, flush=True)


def read_env(path):
    values = {}
    if not path.exists():
        return values

    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def write_env(path, values):
    lines = [
        "# Generated by scripts/setup.py",
        "# Only the network-specific values are required; ports use docker-compose defaults.",
        f"SERVICE_HOST={values['SERVICE_HOST']}",
        f"SPEAKER_IP={values['SPEAKER_IP']}",
    ]

    optional_keys = [
        "AFTERTOUCH_HTTP_PORT",
        "AFTERTOUCH_HTTPS_PORT",
        "PROXY_PORT",
        "BUFFER_SECONDS",
        "BITRATE_KBPS",
        "RECONNECT_BACKOFF_MS",
    ]
    for key in optional_keys:
        value = values.get(key)
        if value and value != DEFAULTS.get(key):
            lines.append(f"{key}={value}")

    path.write_text("\n".join(lines) + "\n")


def get_lan_ip():
    env_host = os.getenv("SERVICE_HOST")
    if env_host and env_host.lower() != "auto":
        return env_host

    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect(("1.1.1.1", 80))
            return sock.getsockname()[0]
    except OSError:
        pass

    try:
        return socket.gethostbyname(socket.gethostname())
    except OSError:
        return "127.0.0.1"


def http_get(url, timeout=2):
    req = urllib.request.Request(url, headers={"User-Agent": "LoseSound-setup/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as response:
        return response.read()


def parse_speaker_info(ip, body):
    try:
        root = ET.fromstring(body)
    except ET.ParseError:
        return None

    xml_text = body.decode("utf-8", errors="ignore")
    attrs = {k.lower(): v for k, v in root.attrib.items()}
    device_id = (
        attrs.get("deviceid")
        or attrs.get("device_id")
        or attrs.get("id")
        or find_text(root, "deviceID")
        or find_text(root, "deviceId")
    )

    looks_like_soundtouch = (
        device_id
        or "SoundTouch" in xml_text
        or "marge" in xml_text.lower()
        or root.tag.lower().endswith("info")
    )
    if not looks_like_soundtouch:
        return None

    return {
        "ip": ip,
        "device_id": device_id or "",
        "name": attrs.get("name") or find_text(root, "name") or "SoundTouch",
        "type": attrs.get("type") or find_text(root, "type") or "",
    }


def find_text(root, name):
    for node in root.iter():
        tag = node.tag.split("}", 1)[-1]
        if tag == name and node.text:
            return node.text.strip()
    return ""


def fetch_speaker(ip, timeout=1.2):
    try:
        body = http_get(f"http://{ip}:8090/info", timeout=timeout)
    except (OSError, urllib.error.URLError, TimeoutError):
        return None
    return parse_speaker_info(ip, body)


def discover_ssdp(timeout=2.0):
    messages = [
        "ssdp:all",
        "urn:schemas-upnp-org:device:MediaRenderer:1",
    ]
    hosts = set()
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP) as sock:
        sock.settimeout(timeout)
        for search_target in messages:
            payload = "\r\n".join(
                [
                    "M-SEARCH * HTTP/1.1",
                    "HOST: 239.255.255.250:1900",
                    'MAN: "ssdp:discover"',
                    "MX: 1",
                    f"ST: {search_target}",
                    "",
                    "",
                ]
            ).encode("ascii")
            try:
                sock.sendto(payload, ("239.255.255.250", 1900))
            except OSError:
                continue

        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                data, address = sock.recvfrom(4096)
            except socket.timeout:
                break
            text = data.decode("iso-8859-1", errors="ignore")
            if "bose" in text.lower() or "soundtouch" in text.lower():
                hosts.add(address[0])
                continue
            for line in text.splitlines():
                if line.lower().startswith("location:"):
                    parsed = urllib.parse.urlparse(line.split(":", 1)[1].strip())
                    if parsed.hostname:
                        hosts.add(parsed.hostname)
    return hosts


def scan_subnet(local_ip):
    try:
        network = ipaddress.ip_network(f"{local_ip}/24", strict=False)
    except ValueError:
        return []

    hosts = [str(ip) for ip in network.hosts()]
    found = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=48) as executor:
        futures = {executor.submit(fetch_speaker, ip, 0.45): ip for ip in hosts}
        for future in concurrent.futures.as_completed(futures):
            speaker = future.result()
            if speaker:
                found.append(speaker)
    return found


def discover_speakers(local_ip, explicit_ip=None):
    if explicit_ip and explicit_ip.lower() != "auto":
        speaker = fetch_speaker(explicit_ip, timeout=2)
        if speaker:
            return [speaker]
        return [{"ip": explicit_ip, "device_id": "", "name": "SoundTouch", "type": ""}]

    candidates = set(discover_ssdp())
    found_by_ssdp = []
    for host in sorted(candidates):
        speaker = fetch_speaker(host, timeout=1.5)
        if speaker:
            found_by_ssdp.append(speaker)

    if found_by_ssdp:
        return found_by_ssdp

    log("Kein Lautsprecher per SSDP gefunden, scanne lokales /24-Netz ...")
    return scan_subnet(local_ip)


def choose_speaker(speakers):
    if not speakers:
        raise RuntimeError("Kein SoundTouch-Lautsprecher gefunden. Starte erneut mit --speaker-ip <IP>.")
    if len(speakers) == 1:
        return speakers[0]

    log("Mehrere SoundTouch-Lautsprecher gefunden:")
    for index, speaker in enumerate(speakers, start=1):
        label = f"{speaker['name']} {speaker['type']}".strip()
        log(f"  {index}. {speaker['ip']}  {label}")

    if not sys.stdin.isatty():
        raise RuntimeError("Mehrere Lautsprecher gefunden. Starte erneut mit --speaker-ip <IP>.")

    while True:
        selected = input("Nummer auswählen: ").strip()
        if selected.isdigit() and 1 <= int(selected) <= len(speakers):
            return speakers[int(selected) - 1]


def wait_for(url, timeout=45):
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            http_get(url, timeout=2)
            return True
        except Exception:
            time.sleep(1)
    return False


def docker_compose_up():
    log("Starte Docker Compose ...")
    subprocess.run(["docker", "compose", "up", "-d", "--build"], cwd=ROOT, check=True)


def migrate_speaker(service_host, speaker, env):
    device_id = speaker.get("device_id")
    if not device_id:
        log("Migration übersprungen: Lautsprecher liefert keine deviceID über /info.")
        return False

    port = env.get("AFTERTOUCH_HTTP_PORT", DEFAULTS["AFTERTOUCH_HTTP_PORT"])
    target_url = f"http://{service_host}:{port}"
    query = urllib.parse.urlencode({"target_url": target_url})
    local_url = f"http://127.0.0.1:{port}/setup/migrate/{urllib.parse.quote(device_id)}?{query}"

    log(f"Führe Migration für Gerät {device_id} aus ...")
    try:
        http_get(local_url, timeout=20)
    except Exception as exc:
        log(f"Migration konnte nicht automatisch bestätigt werden: {exc}")
        log(f"Öffne alternativ manuell: http://{service_host}:{port}/setup/migrate/{device_id}?{query}")
        return False

    log("Migration wurde an AfterTouch gesendet.")
    return True


def main():
    parser = argparse.ArgumentParser(description="Automatisches LoseSound Setup")
    parser.add_argument("--service-host", help="LAN-IP dieses Docker-Hosts")
    parser.add_argument("--speaker-ip", help="IP des SoundTouch-Lautsprechers")
    parser.add_argument("--no-start", action="store_true", help="Nur .env schreiben, Docker nicht starten")
    parser.add_argument("--migrate", action="store_true", help="AfterTouch-Migration nach dem Start automatisch ausführen")
    args = parser.parse_args()

    env = read_env(ENV_PATH)
    service_host = args.service_host or os.getenv("SERVICE_HOST") or get_lan_ip()
    speaker_ip = args.speaker_ip or os.getenv("SPEAKER_IP")

    log(f"Docker-Host-IP: {service_host}")
    speakers = discover_speakers(service_host, speaker_ip)
    if not speakers and env.get("SPEAKER_IP"):
        log("Nutze SPEAKER_IP aus bestehender .env als Fallback ...")
        speakers = discover_speakers(service_host, env["SPEAKER_IP"])
    speaker = choose_speaker(speakers)
    log(f"SoundTouch: {speaker['ip']} {speaker.get('name', '')}".strip())

    env.update({"SERVICE_HOST": service_host, "SPEAKER_IP": speaker["ip"]})
    write_env(ENV_PATH, env)
    log(f".env aktualisiert: {ENV_PATH}")

    if args.no_start:
        return

    docker_compose_up()

    port = env.get("AFTERTOUCH_HTTP_PORT", DEFAULTS["AFTERTOUCH_HTTP_PORT"])
    if wait_for(f"http://127.0.0.1:{port}", timeout=60):
        log("AfterTouch ist erreichbar.")
    else:
        log("AfterTouch war nach 60 Sekunden noch nicht erreichbar.")
        return

    if args.migrate:
        migrate_speaker(service_host, speaker, env)
    else:
        log("Migration übersprungen. Nutze dafür die AfterTouch Web UI oder starte erneut mit --migrate.")

    proxy_port = env.get("PROXY_PORT", DEFAULTS["PROXY_PORT"])
    log(f"Preset UI: http://{service_host}:{proxy_port}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        sys.exit(130)
    except Exception as exc:
        log(f"Fehler: {exc}")
        sys.exit(1)
